"""add column priority to projects table

Revision ID: 6eaee7ad3f7b
Revises: 199f22d0a21e
Create Date: 2024-11-02 01:59:11.664041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eaee7ad3f7b'
down_revision: Union[str, None] = '199f22d0a21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('priority', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'priority')
    # ### end Alembic commands ###
